name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README Translations
        uses: ikhsan3adi/markdown-translator@master
        with:
          LANG: |-
            id
            zh-CN
            zh-TW
            hi
            ar
            fr
